# Generated by Django 5.2.4 on 2025-07-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('photo_path', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
