# Generated by Django 5.2.4 on 2025-07-28 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_birthday_delete_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Birthday',
        ),
    ]
