# Generated by Django 5.2.4 on 2025-08-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_delete_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_code', models.IntegerField()),
                ('dob', models.DateField()),
                ('img', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
