# Generated by Django 5.2.4 on 2025-08-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='emp_code',
            field=models.IntegerField(unique=True),
        ),
    ]
